version: '3.8'

services:
  rowboat:
    build:
      context: ./apps/rowboat
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - OXYLABS_USERNAME=${OXYLABS_USERNAME}
      - OXYLABS_PASSWORD=${OXYLABS_PASSWORD}
      - CHAT_WIDGET_SESSION_JWT_SECRET=${CHAT_WIDGET_SESSION_JWT_SECRET}
      - AGENTS_API_URL=http://agents:3001
      - AGENTS_API_KEY=${AGENTS_API_KEY}
      - COPILOT_API_URL=http://copilot:3002
      - COPILOT_API_KEY=${COPILOT_API_KEY}
      - AUTH0_SECRET=${AUTH0_SECRET}
      - AUTH0_BASE_URL=${AUTH0_BASE_URL}
      - AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - REDIS_URL=redis://redis:6379
      - MAX_QUERIES_PER_MINUTE=${MAX_QUERIES_PER_MINUTE}
      - MAX_PROJECTS_PER_USER=${MAX_PROJECTS_PER_USER}
    restart: unless-stopped

  agents:
    build:
      context: ./apps/agents
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_KEY=${AGENTS_API_KEY}
    restart: unless-stopped

  copilot:
    build:
      context: ./apps/copilot
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_KEY=${COPILOT_API_KEY}
    restart: unless-stopped

  tools_webhook:
    build:
      context: ./apps/tools_webhook
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - SIGNING_SECRET=${SIGNING_SECRET}
    restart: unless-stopped 

  simulation_runner:
    build:
      context: ./apps/simulation_runner
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=${MONGODB_CONNECTION_STRING}
      - ROWBOAT_API_HOST=http://rowboat:3000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped

  docs:
    build:
      context: ./apps/docs
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
